# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy go.mod and go.sum then download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the remaining source code
COPY . .

# Build the server binary with CGO disabled
RUN CGO_ENABLED=0 go build -o think-tool server.go

FROM alpine:latest
WORKDIR /app

# Copy the built binary from the builder stage
COPY --from=builder /app/think-tool ./think-tool

CMD ["./think-tool"]
