name: Release Go Binaries

on: 
  push:
    tags:
      - 'v*'

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF#refs/tags/}) >> ${GITHUB_ENV}
    - name: Set BUILD_TIME env
      run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}


    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: think-tool
        compress_assets: OFF
        md5sum: false
        sha256sum: false
        goversion: "https://dl.google.com/go/go1.24.1.linux-amd64.tar.gz"
        build_flags: -v
        ldflags: -s -w -X "main.appVersion=${{ env.APP_VERSION }}" -X "main.buildTime=${{ env.BUILD_TIME }}" -X "main.gitCommit=${{ github.sha }}" -X "main.gitRef=${{ github.ref }}"